//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuulariApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public int Visibility { get; set; }
        public int Theme { get; set; }
        public bool Sync { get; set; }
        public Nullable<byte> SyncFrequency { get; set; }
        public string Interests { get; set; }
        public Nullable<int> MarkerHue { get; set; }
    
        public virtual User User { get; set; }
    }
}
